#!/usr/bin/env node

'use strict';

const compiler = require('./index.js');
const argv = require('yargs').usage('Usage: $0 path/to/rules.yaml').demand(1).argv;
const fs = require('fs');
const yaml = require('js-yaml');

const rawSource = fs.readFileSync(argv._[0], 'utf8');
const source = yaml.load(rawSource, {filename: argv._[0], schema: yaml.DEFAULT_SAFE_SCHEMA});
const rules = compiler.transform(source);
// console.log(JSON.stringify(rules, null, 2));
fs.writeFileSync(
  argv._[0].replace(/\.ya?ml$/, '') + '.json',
  JSON.stringify({rules: rules.rules}, null, 2)
);
if (rules.firecrypt) {
  fs.writeFileSync(
    argv._[0].replace(/\.ya?ml$/, '') + '_firecrypt.json',
    JSON.stringify({rules: rules.firecrypt}, null, 2)
  );
}
