#!/usr/bin/env node

'use strict';

const compiler = require('./index.js');
const argv = require('yargs')
  .option('o', {alias: 'output', describe: 'output path', type: 'string'})
  .usage('$0 <input>', 'transform a fireplan rules file into a JSON rules file', yargs => {
    yargs.positional('input', {
      describe: 'the fireplan rules input file',
      type: 'string'
    });
  })
  .strict()
  .argv;

compiler.transformFile(argv.input, argv.output);
