'use strict';

const _ = require('lodash');
const esprima = require('esprima');

class TypeGenerator {
  constructor(source) {
    this.source = source;
    this.functionTypes = {
      string: 'string',
      number: 'number',
      boolean: 'boolean',
      any: 'any'
    };
    this.functionDefinitions = {};
    this.loadFunctionDefinitions();
    this.resolveFunctionTypes();
  }

  loadFunctionDefinitions() {
    _.forEach(this.source.functions || [], definition => {
      _.forEach(definition, (body, signature) => {
        const match = signature.match(/^\s*(\w+)\s*(?:\((.*?)\))?\s*$/);
        if (!match) return;
        const name = match[1];
        const args = _.compact(_.map((match[2] || '').split(','), _.trim));
        this.functionDefinitions[name] = {body, args};
      });
    });
  }

  resolveFunctionTypes() {
    let changed = true;
    while (changed) {
      changed = false;
      const definitions = Object.entries(this.functionDefinitions);
      for (const [name, definition] of definitions) {
        if (definition.args.length) continue;
        const inferredType = this.inferExpressionType(definition.body);
        const shouldUpdate =
          inferredType && inferredType !== 'unknown' && this.functionTypes[name] !== inferredType;
        if (shouldUpdate) {
          this.functionTypes[name] = inferredType;
          changed = true;
        }
      }
    }
  }

  inferExpressionType(expression) {
    if (!_.isString(expression)) return 'unknown';
    const parsed = this.parseConstraint(expression);
    return this.disjunctionType(parsed.expression) ||
      this.inferSingleExpressionType(parsed.expression) ||
      'unknown';
  }

  disjunctionType(expression) {
    const parts = this.disjunctionParts(expression);
    if (parts.length <= 1) return;

    const inferredTypes = _(parts)
      .map(part => this.inferSingleExpressionType(part))
      .filter(type => type && type !== 'unknown')
      .flatMap(type => _.map(type.split('|'), _.trim))
      .uniq()
      .value();

    if (!inferredTypes.length) return;
    return inferredTypes.join(' | ');
  }

  inferSingleExpressionType(expression) {
    return this.oneOfType(expression) ??
      this.resolveFunctionReferenceType(expression);
  }

  disjunctionParts(expression) {
    if (!_.isString(expression) || !_.includes(expression, '||')) return [expression];

    let parsed;
    try {
      parsed = esprima.parseScript(expression, {range: true});
    } catch (error) {
      void error;
      return _.map(expression.split('||'), _.trim);
    }

    if (!parsed.body.length || parsed.body[0].type !== 'ExpressionStatement') return [expression];

    const parts = [];
    const stack = [parsed.body[0].expression];
    while (stack.length) {
      const node = stack.pop();
      if (node.type === 'LogicalExpression' && node.operator === '||') {
        stack.push(node.right);
        stack.push(node.left);
        continue;
      }
      if (!node.range) return _.map(expression.split('||'), _.trim);
      parts.push(_.trim(expression.slice(node.range[0], node.range[1])));
    }
    return parts;
  }

  generate() {
    const root = this.toNode(this.source.root || {});
    return [
      '// Generated by fireplan. Do not edit directly.',
      '',
      `export type FirebaseData = ${this.typeString(root, 0)}`,
      ''
    ].join('\n');
  }

  typeString(node, indent) {
    if (node.kind !== 'object') return node.type;
    const keepStaticEntries = !_.some(node.entries, {wildcard: true}) || node.moreAllowed;
    const rows = ['{'];
    _.forEach(node.entries, entry => {
      const type = this.typeString(entry.node, indent + 2);
      const required = entry.required || entry.wildcard || type === 'any';
      if (entry.wildcard || keepStaticEntries) {
        const key = entry.wildcard ? `[${entry.key}: string]` : entry.key;
        rows.push(`${_.repeat(' ', indent + 2)}${key}${required ? '' : '?'}: ${type}`);
      }
    });
    if (node.moreAllowed) rows.push(`${_.repeat(' ', indent + 2)}[key: string]: any`);
    rows.push(`${_.repeat(' ', indent)}}`);
    return rows.join('\n');
  }

  toNode(yaml) {
    if (_.isString(yaml)) return this.fromConstraint(yaml);
    if (!_.isObject(yaml) || _.isArray(yaml)) return {kind: 'leaf', type: 'unknown'};
    const childKeys = _.filter(_.keys(yaml), key => key.charAt(0) !== '.');
    if (!childKeys.length) {
      if ('.value' in yaml) return this.fromConstraint(yaml['.value']);
      if (yaml['.more']) return {kind: 'leaf', type: 'any'};
      return {kind: 'leaf', type: 'unknown'};
    }
    return {
      kind: 'object',
      moreAllowed: yaml['.more'] === true,
      entries: _.map(childKeys, key => {
        const value = yaml[key];
        const constraint = _.isString(value) ? value : value && value['.value'];
        const wildcard = key.charAt(0) === '$';
        return {
          key: wildcard ? this.wildcardName(key.slice(1)) : this.propertyName(key),
          wildcard,
          required: wildcard || this.isRequired(constraint),
          node: this.toNode(value)
        };
      })
    };
  }

  wildcardName(key) {
    key = key.replace(/\/.*/, '');
    return key.match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? key : 'key';
  }

  propertyName(key) {
    key = key.replace(/\/.*/, '');
    return key.match(/^[$a-zA-Z_][a-zA-Z0-9_$]*$/) ? key : JSON.stringify(key);
  }

  parseConstraint(constraint) {
    if (!_.isString(constraint)) return {keywords: {}, expression: ''};
    let rest = constraint;
    const keywords = {};
    while (true) {
      const match = rest.match(/^\s*(required|indexed|encrypted(?:\[.*?\])?)(?:\s+|$)/);
      if (!match) break;
      const keyword = _.startsWith(match[1], 'encrypted') ? 'encrypted' : match[1];
      keywords[keyword] = true;
      rest = rest.slice(match[0].length);
    }
    return {keywords, expression: _.trim(rest)};
  }

  isRequired(constraint) {
    return this.parseConstraint(constraint).keywords.required === true;
  }

  fromConstraint(constraint) {
    if (!_.isString(constraint)) return {kind: 'leaf', type: 'unknown'};
    const inferredType = this.inferExpressionType(constraint);
    return {kind: 'leaf', type: inferredType || 'unknown'};
  }

  resolveFunctionReferenceType(expression) {
    if (!_.isString(expression)) return;
    const bareNameMatch = expression.match(/^(\w+)\b/);
    if (!bareNameMatch) return;
    const name = bareNameMatch[1];
    const definition = this.functionDefinitions[name];
    if (definition && definition.args.length) return;
    return this.functionTypes[name];
  }

  oneOfType(expression) {
    const match = expression.match(/^\s*oneOf\s*\(([\s\S]*?)\)/);
    if (!match) return;
    let parsed;
    try {
      parsed = esprima.parse(`oneOf(${match[1]})`).body[0].expression;
    } catch (error) {
      void error;
      return;
    }
    if (!parsed || parsed.type !== 'CallExpression' || parsed.callee.name !== 'oneOf') return;
    return _.map(parsed.arguments, arg => {
      if (arg.type === 'Literal') return JSON.stringify(arg.value);
      return 'unknown';
    }).join(' | ');
  }
}

exports.generateTypes = function(source) {
  return new TypeGenerator(source).generate();
};
